### ISSUE TITLE
Reconcile /projects and /products

### ISSUE THREAD

**Issue by illright** [VanishMax/innopoints-frontend#101]
As of now, all URLs for products use `/product` and all URLs for projects use `/projects`. This causes bugs like 
https://github.com/VanishMax/innopoints-frontend/blob/42a8cdf415f9e4fe746c2dd605218878d4053ae6/src/components/profile/timeline-entry.svelte#L72

where the URL should have been pointing to `/product`.

**Proposed solution**: make both plural.

**Comment by aabounegm** [comment]
Actually, the usage of `/projects` is not even consistent. In some places, `/project/new` is used, such as:
https://github.com/VanishMax/innopoints-frontend/blob/9795f0baeecb35b8dd6ce496d53fd04d2d25b6a5/src/routes/projects/past.svelte#L77 and https://github.com/VanishMax/innopoints-frontend/blob/9795f0baeecb35b8dd6ce496d53fd04d2d25b6a5/src/routes/projects/index.svelte#L99
