### ISSUE TITLE
The "start date" and "end date" buttons are not functioning

### ISSUE THREAD

**Issue by illright** [VanishMax/innopoints-frontend#21]
The expected behaviour: 
- when in the "start date" mode, the press on the "end date" button should select today as the stat date and switch the user to the "end date" mode
- when in the "end date" mode, the press on the "start date" button should switch the user to the "start date" mode, while, if possible, still retaining the previous selection on screen so that the user can see and correct their mistake

**Comment by VanishMax** [comment]
Closed in [the commit](https://github.com/VanishMax/innopoints-frontend/pull/16/commits/e9ef75910fcfd49fce83311cf959c28414ea1d37)
