### ISSUE TITLE
Refactor the day classes in the calendar

### ISSUE THREAD

**Issue by illright** [VanishMax/innopoints-frontend#24]
Considering that we will now have a `.day` class on every day, the following changes to the classes should be made:
- the days outside the month should be `.day.outside`
- the current day should be `.day.today`
- the first day in the selection should be `.day.in-range.start`
- the intermediate days in the selection should be `.day.in-range`
- the last day in the selection should be `.day.in-range.end`

**Comment by VanishMax** [comment]
Fixed in the commit above
