### ISSUE TITLE
Purchase status modification

### ISSUE THREAD

**Issue by illright** [VanishMax/innopoints-frontend#56]
In the Admin Dashboard, the Purchases card, all of the purchases except for the **rejected** and **delivered** ones are listed. Below them is a row of buttons:
![image](https://user-images.githubusercontent.com/15035286/71446700-08fabc80-2748-11ea-9c11-9807f9050285.png)
When one of them is pressed (e.g. ready for pickup), the following message is displayed:
![image](https://user-images.githubusercontent.com/15035286/71446711-23cd3100-2748-11ea-9926-a0347cd2a77c.png)
And then, if you click on "edit status", you will not see the selected status, and instead, "pending" will take its place:
![image](https://user-images.githubusercontent.com/15035286/71446769-cab1cd00-2748-11ea-986c-9c755e4bc8a3.png)
The icon used for the pending button is `archive`.

**Comment by aabounegm** [comment]
\*insert "but.. why?" gif\*
It is not intuitive that "pending" would mean "leave it in its current state, ready for pickup"

**Comment by illright** [comment]
@aabounegm because it wouldn't mean that? It means get the purchase back into pending state. In case they mistakenly marked the purchase as ready

**Comment by aabounegm** [comment]
oh. so how to cancel editing then?

**Comment by illright** [comment]
@aabounegm Well, pretty much refresh the page. Yeah, it sucks, I have an idea for something else, but don't care too much about it now

**Comment by VanishMax** [comment]
Implemented in #60
